Repository FEMessage/el-data-table, pull requests merged in 2019-09, with the labels that each got.

#211 fix: 使用需要弹窗的功能并把 hasDialog 设置为 false 时, 将会报错
  src/el-data-table.vue
Labels: bug

#212 feat: slot-form增加作用域数据
  docs/slot-form.md
  src/components/the-dialog.vue
  src/el-data-table.vue
Labels: enhancement

#217 refactor: remove hasDialog related code
  src/el-data-table.vue
Labels: refactor

#215 feat: 搜索表单支持定位插槽
  docs/slot-search.md
  src/components/search-form.vue
  src/el-data-table.vue
  src/utils/extract-keys.js
  test/extract-keys.test.js
Labels: enhancement

#221 feat: 支持切换操作栏按钮风格
  src/el-data-table.vue
Labels: enhancement

#220 feat: 支持统一定制按钮大小
  docs/guide-contributing-correctly.md
  src/components/the-dialog.vue
  src/el-data-table.vue
Labels: enhancement
