Repository FEMessage/el-data-table, pull requests merged in 2019-11, with the labels that each got.

#228 fix: 删完最后一页后页码不正确的问题
  .eslintignore
  .eslintrc.js
  docs/basic.md
  package.json
  src/el-data-table.vue
  yarn.lock
Labels: bug

#229 docs: 更新mock接口
  docs/basic.md
  docs/before-search.md
  docs/clear-selection.md
  docs/expand.md
  docs/extra-body.md
  docs/extra-buttons.md
  docs/first-page.md
  docs/has-pagination=false.md
  docs/id.md
  docs/is-tree.md
  docs/new-text.md
  docs/on-new-edit-delete.md
  docs/persist-selection.md
  docs/save-query.md
  docs/search-item-collapsible.md
  docs/slot-form.md
  docs/slot-header.md
  docs/slot-no-data.md
Labels: documentation

#230 docs: 更换图床
  README-zh.md
  README.md
  docs/faq.md
Labels: documentation

#231 fix: 修改 no-data slot 逻辑
  package.json
  src/el-data-table.vue
  src/utils/is-falsey.js
  test/is-falsey.test.js
  yarn.lock
Labels: bug

#235 fix: 修复树形表数据无法直接stringify的问题
  src/el-data-table.vue
Labels: bug

#240 docs(formatter): 增加 formatter 使用 jsx 的演示
  docs/formatter.md
  styleguide.config.js
Labels: documentation

#239 fix: onDelete没有抛出异常的问题
  src/el-data-table.vue
Labels: bug

#242 docs: 让文档在 CI 环境下不报错
  docs/formatter.md
Labels: documentation

#246 feat: 刷新列表时提供一个 flag 判断是否显示 loading
  src/el-data-table.vue
Labels: enhancement

#245 feat: 暴露 correctPage API
  docs/faq.md
  src/el-data-table.vue
Labels: enhancement

#247 feat: extraButton添加函数类型的disabled属性
  docs/extra-buttons.md
  src/el-data-table.vue
Labels: enhancement

#248 docs: 补充 searchImmediately 文档
  docs/search-immediately.md
  src/el-data-table.md
Labels: documentation
