Repository FEMessage/el-data-table, pull requests merged in 2019-07, with the labels that each got.

#150 fix: self-loading-button在header处应该是el-button样式
  src/el-data-table.vue
  src/self-loading-button.vue
Labels: bug

#154 docs: add english readme
  README-en.md
Labels: enhancement

#156 feat(deps): upgrade `@femessage/el-form-renderer` to `1.6.0`
  README-en.md
  README.md
  docs/basic.md
  docs/before-confirm.md
  docs/before-search.md
  docs/can-search-collapse.md
  docs/extra-body.md
  docs/extra-query.sync.md
  docs/faq.md
  docs/first-page.md
  docs/has-pagination=false.md
  docs/is-tree.md
  docs/on-new-edit-delete.md
  docs/router-mode=history.md
  docs/save-query.md
  docs/slot-search.md
  package.json
  yarn.lock
Labels: enhancement

#112 feat(extraButton): text 接受函数
  docs/extra-buttons.md
  docs/header-buttons.md
  src/el-data-table.vue
Labels: enhancement

#104 feat: 可配置默认按钮文字
  docs/new-text.md
  src/el-data-table.vue
Labels: enhancement

#157 feat: 抽离table选中逻辑
  docs/clear-selection.md
  docs/persist-selection.md
  src/el-data-table.vue
  src/utils/select-strategy.js
  test/select-strategy.test.js
Labels: enhancement

#161 docs(faq): 记录通过v-if切换el-data-table时出现无法重置searchForm的问题
  docs/faq.md
Labels: documentation

#159 refactor: remove router mode
  docs/router-mode=history.md
  src/el-data-table.vue
Labels: refactor

#169 chore: scope package name
  README-en.md
  README.md
  package.json
Labels: chore

#165 feat: 增加no-data slot
  .gitignore
  docs/slot-no-data.md
  src/el-data-table.vue
Labels: enhancement

#163 fix: getList在mounted阶段会发出两次
  src/el-data-table.vue
Labels: bug

#173 docs: README弃用新浪图床使用语雀cdn
  README.md
Labels: documentation

#171 refactor: 优化dialog冗余代码
  src/components/self-loading-button.vue
  src/components/text-button.vue
  src/el-data-table.vue
Labels: refactor

#177 feat: 增加header-slot
  docs/slot-header.md
  src/el-data-table.vue
Labels: enhancement

#180 chore: 更新 cli 配置
  .stylelintrc
  notify.sh
  package.json
  styleguide.config.js
  yarn.lock
Labels: chore

#179 fix: 修复 tr 淡入动画没添加上
  src/el-data-table.vue
Labels: bug

#183 fix: header 在没有头部按钮时出现 22px 高度的问题
  src/el-data-table.vue
Labels: bug

#184 docs: update README badges & contributing
  .github/badge.yml
  .grenrc.js
  .travis.yml
  README-en.md
  README.md
  package.json
Labels: documentation
