Repository FEMessage/el-data-table, pull requests merged in 2019-08, with the labels that each got.

#189 fix: error 422 when fetch github api without query 「q」
  docs/slot-search.md
Labels: bug

#187 docs: expose resetSearch as public method in api document
  src/el-data-table.vue
Labels: documentation

#194 chore: 执行prettier & stylus => less
  README-en.md
  README.md
  build/rollup.config.js
  package.json
  src/components/the-dialog.vue
  src/el-data-table.vue
  src/index.js
  styleguide.config.js
  yarn.lock
Labels: chore

#206 docs: `extraQuery`的正确使用方法
  docs/extra-query.sync.md
Labels: documentation

#204 refactor: 删除逻辑使用async/await精简代码
  src/el-data-table.vue
Labels: refactor

#201 feat: 支持设置对话框属性 dialogAttrs
  src/components/the-dialog.vue
  src/el-data-table.vue
Labels: enhancement

#205 feat: searchForm 内容支持属性 collapsible=false，在搜索区域折叠后仍可见
  docs/search-item-collapsible.md
  src/components/search-form.vue
  src/el-data-table.vue
  yarn.lock
Labels: enhancement
