Repository FEMessage/el-data-table, pull requests merged in 2019-12, with the labels that each got.

#249 fix: 修复 el-pagination 值错误，可点击问题
  src/el-data-table.vue
Labels: bug

#252 fix: header 部分仅有 slot-header 时，该 slot 未显示的 bug
  src/el-data-table.vue
Labels: bug

#253 feat: 支持多级表头
  docs/multi-level-header.md
  src/components/el-data-table-column.js
  src/el-data-table.vue
Labels: enhancement

#255 fix: getList 出错时设置 total = 0
  src/el-data-table.vue
  yarn.lock
Labels: bug

#261 chore(deps): upgrade gren
  .grenrc.js
  package.json
  yarn.lock
Labels: dependencies

#265 feat: 支持配置axios的config
  docs/axios-config.md
  src/el-data-table.vue
Labels: enhancement

#266 feat: 自定义删除弹窗文案
  docs/custom-text.md
  src/el-data-table.vue
Labels: enhancement

#269 feat: 新增 onSuccess 钩子
  docs/on-success.md
  src/el-data-table.vue
Labels: enhancement

#270 feat: 添加分页自定义 key
  src/el-data-table.vue
Labels: enhancement

#272 fix: columns property align not work
  docs/basic.md
  src/components/el-data-table-column.js
  src/el-data-table.vue
Labels: bug

#274 fix: 折叠 与 `el-form-renderer.remote` 功能冲突
  docs/search-item-collapsible.md
  src/components/search-form.vue
  src/el-data-table.vue
Labels: bug

#275 docs: 公开 onDefaultDelete 方法
  docs/on-default-delete.md
  src/el-data-table.vue
Labels: documentation

#243 refactor: 通过 props 的 default 属性简化代码层级
  docs/on-new-edit-delete.md
  src/el-data-table.vue
Labels: refactor
